# Generated by Django 6.0.4 on 2026-04-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0003_tbl_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
            ],
        ),
    ]
