# Generated by Django 6.0.4 on 2026-05-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0007_tbl_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_brand',
        ),
    ]
