# Generated by Django 6.0.4 on 2026-05-04 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0009_tbl_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_brand')),
            ],
        ),
    ]
