# Generated by Django 6.0.4 on 2026-05-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0012_tbl_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_models',
        ),
    ]
