# Generated by Django 6.0.4 on 2026-05-08 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0014_tbl_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_scraprate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraprate_rate', models.IntegerField(null=True)),
                ('scraprate_date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_category')),
            ],
        ),
    ]
