# Generated by Django 6.0.4 on 2026-04-22 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_cpassword',
        ),
    ]
