# Generated by Django 6.0.4 on 2026-04-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_remove_tbl_user_user_cpassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
