# Generated by Django 6.0.4 on 2026-04-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_scrapcenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scarpcenter_name', models.CharField(max_length=50)),
                ('scarpcenter_email', models.CharField(max_length=50)),
            ],
        ),
    ]
