# Generated by Django 6.0.4 on 2026-04-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_scrapcenter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_scrapcenter',
        ),
    ]
