# Generated by Django 6.0.4 on 2026-05-01 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_tbl_scrapcenter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_scrapcenter',
        ),
    ]
