# Generated by Django 6.0.4 on 2026-05-01 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0007_tbl_subcategory'),
        ('Guest', '0012_delete_tbl_scrapcenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_scrapcenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrapcenter_name', models.CharField(max_length=50)),
                ('scrapcenter_email', models.CharField(max_length=50)),
                ('scrapcenter_contact', models.CharField(max_length=50)),
                ('scrapcenter_address', models.CharField(max_length=50)),
                ('scrapcenter_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('scrapcenter_proof', models.FileField(upload_to='Assets/UserDocs/')),
                ('scarpcenter_password', models.CharField(max_length=50)),
                ('scrapcenter_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
