# Generated by Django 6.0.4 on 2026-05-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0013_tbl_scrapcenter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_scrapcenter',
            old_name='scarpcenter_password',
            new_name='scrapcenter_password',
        ),
    ]
