# Generated by Django 6.0.4 on 2026-04-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmpt_title', models.CharField(max_length=50)),
                ('cmpt_content', models.CharField(max_length=50)),
            ],
        ),
    ]
