# Generated by Django 6.0.4 on 2026-04-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_content', models.CharField(max_length=50)),
                ('fb_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
