# Generated by Django 6.0.4 on 2026-05-01 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0014_rename_scarpcenter_password_tbl_scrapcenter_scrapcenter_password'),
        ('User', '0007_delete_tbl_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmpt_title', models.CharField(max_length=50)),
                ('cmpt_content', models.CharField(max_length=50)),
                ('cmpt_date', models.DateField(auto_now_add=True)),
                ('cmpt_status', models.IntegerField(default=0)),
                ('cmpt_reply', models.CharField(max_length=50, null=True)),
                ('scrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_scrapcenter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
