# Generated by Django 6.0.4 on 2026-05-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_tbl_addvehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_addvehicle',
        ),
    ]
