# Generated by Django 6.0.4 on 2026-05-07 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0014_tbl_model'),
        ('Guest', '0014_rename_scarpcenter_password_tbl_scrapcenter_scrapcenter_password'),
        ('User', '0014_delete_tbl_addvehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_addvehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture_yr', models.IntegerField(null=True)),
                ('fuel_type', models.CharField(max_length=50)),
                ('transmission_type', models.CharField(max_length=50)),
                ('vehicle_mileage', models.IntegerField(null=True)),
                ('vehicle_condition', models.CharField(max_length=50)),
                ('is_rc_available', models.BooleanField()),
                ('insurance_status', models.BooleanField()),
                ('vehicle_description', models.TextField(max_length=50)),
                ('vehicle_status', models.IntegerField(null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
