# Generated by Django 6.0.4 on 2026-05-08 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_tbl_addvehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_file', models.FileField(upload_to='Assets/UserDocs/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_addvehicle')),
            ],
        ),
    ]
