# Generated by Django 6.0.5 on 2026-05-27 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0014_rename_scarpcenter_password_tbl_scrapcenter_scrapcenter_password'),
        ('User', '0017_tbl_sendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('scrapcenter_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrapcenter_from', to='Guest.tbl_scrapcenter')),
                ('scrapcenter_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scrapcenter_to', to='Guest.tbl_scrapcenter')),
                ('user_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='Guest.tbl_user')),
                ('user_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='Guest.tbl_user')),
            ],
        ),
    ]
