# Generated by Django 6.0.5 on 2026-05-27 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_tbl_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_chat',
        ),
    ]
