# Generated by Django 6.0.5 on 2026-05-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_tbl_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_addvehicle',
            name='vehicle_status',
            field=models.IntegerField(default=0),
        ),
    ]
