# Generated by Django 6.0.5 on 2026-05-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_alter_tbl_addvehicle_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_addvehicle',
            name='vehicle_status',
            field=models.IntegerField(null=True),
        ),
    ]
