# Generated by Django 6.0.4 on 2026-05-11 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrapcenter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
