# Generated by Django 6.0.4 on 2026-05-13 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrapcenter', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_request',
        ),
    ]
