# Generated by Django 6.0.4 on 2026-05-13 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0014_rename_scarpcenter_password_tbl_scrapcenter_scrapcenter_password'),
        ('Scrapcenter', '0004_delete_tbl_request'),
        ('User', '0016_tbl_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_status', models.IntegerField(default=0)),
                ('request_amount', models.CharField(max_length=50, null=True)),
                ('request_remark', models.CharField(max_length=50, null=True)),
                ('scrapcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_scrapcenter')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_addvehicle')),
            ],
        ),
    ]
